"""Ablation table (SPEC §6; PRD FR-7/FR-9): random / bm25 / dense / hybrid / full
on a split, showing each stage's contribution. Writes reports/ablation.md.

  python scripts/ablation.py --split tune
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from semsearch.data import load_eval, load_pois  # noqa: E402
from semsearch.engines import (  # noqa: E402
    make_bm25_ranker,
    make_dense_ranker,
    make_full_ranker,
    make_hybrid_ranker,
    make_random_ranker,
)
from semsearch.eval import evaluate  # noqa: E402
from semsearch.split import SPLIT_PATH, load_split, make_split, select  # noqa: E402

REPORTS = Path("reports")
STAGES = [
    ("random", lambda pois: make_random_ranker(pois, seed=0)),
    ("bm25", make_bm25_ranker),
    ("dense", make_dense_ranker),
    ("hybrid", make_hybrid_ranker),
    ("full (+re-rank)", make_full_ranker),
]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--split", default="tune", choices=["tune", "test", "all"])
    args = ap.parse_args()

    pois = load_pois()
    queries = load_eval()
    if args.split != "all":
        split = load_split() if SPLIT_PATH.exists() else make_split(queries)
        queries = select(queries, split, args.split)

    lines = [
        f"# Ablation ({args.split} split, n={len(queries)})",
        "",
        "Each retrieval/ranking stage's contribution "
        "(generated by `scripts/ablation.py`).",
        "",
        "| Stage | Recall@3 | Recall@5 | NDCG@5 | MRR |",
        "|---|---|---|---|---|",
    ]
    for name, factory in STAGES:
        res = evaluate(factory(pois), queries)["overall"]
        lines.append(
            f"| {name} | {res['recall@3']:.3f} | {res['recall@5']:.3f} | "
            f"{res['ndcg@5']:.3f} | {res['mrr']:.3f} |"
        )

    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / f"ablation-{args.split}.md"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
