"""Provider comparison for the embedding choice (RUNBOOK Phase 3, PRD FR-10).

Evaluates dense retrieval per available provider on the TUNE split and writes
reports/embedding-choice.md. Local bge-m3 is the primary (D1); Bedrock providers
are compared only when credentials are present (never required — NFR-3).

  python scripts/embedding_choice.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from semsearch.data import load_eval, load_pois  # noqa: E402
from semsearch.embeddings import get_embedder  # noqa: E402
from semsearch.engines import make_dense_ranker  # noqa: E402
from semsearch.eval import evaluate  # noqa: E402
from semsearch.split import SPLIT_PATH, load_split, make_split, select  # noqa: E402

REPORTS = Path("reports")
CANDIDATES = ["local", "bedrock-cohere", "bedrock-titan"]


def main() -> None:
    pois = load_pois()
    queries = load_eval()
    split = load_split() if SPLIT_PATH.exists() else make_split(queries)
    tune = select(queries, split, "tune")

    rows: list[tuple[str, str, dict | None]] = []
    for name in CANDIDATES:
        try:
            get_embedder(name)  # raises SystemExit if not wired / no creds
        except SystemExit as exc:
            rows.append((name, f"skipped ({exc})", None))
            continue
        try:
            res = evaluate(make_dense_ranker(pois, provider=name), tune)
            rows.append((name, "ok", res["overall"]))
        except Exception as exc:  # noqa: BLE001 - provider/runtime failure is informational
            rows.append((name, f"error ({type(exc).__name__})", None))

    REPORTS.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Embedding provider comparison",
        "",
        "Dense-retrieval quality per provider on the **tune** split "
        "(generated by `scripts/embedding_choice.py`).",
        "",
        "| Provider | Model | Status | Recall@5 | NDCG@5 |",
        "|---|---|---|---|---|",
    ]
    from semsearch.embeddings import MODEL_IDS

    best = None
    for name, status, overall in rows:
        model = MODEL_IDS.get(name, "-")
        if overall:
            r5, n5 = overall["recall@5"], overall["ndcg@5"]
            lines.append(f"| {name} | `{model}` | {status} | {r5:.3f} | {n5:.3f} |")
            if best is None or n5 > best[1]:
                best = (name, n5)
        else:
            lines.append(f"| {name} | `{model}` | {status} | — | — |")

    lines += [
        "",
        f"**Chosen: `local` (bge-m3)** — primary provider per D1 (local-first). "
        f"{'Best measured NDCG@5: ' + f'`{best[0]}` ({best[1]:.3f}).' if best else ''}",
        "",
        "Bedrock providers are compared only when AWS credentials are available; the "
        "demo path never depends on them (NFR-3).",
        "",
    ]
    out = REPORTS / "embedding-choice.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
