"""Consolidated metrics report (PRD FR-9, §6; submission deliverable).

Writes reports/metrics.md: the G1-G5 gate summary + the held-out test headline
(with bootstrap CI, per-difficulty and per-category breakdown). Pulls latency
(G4) and robustness (G5) from their JSON artifacts. Script-generated.

  python scripts/report_metrics.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from semsearch.data import load_eval, load_pois  # noqa: E402
from semsearch.engines import (  # noqa: E402
    make_bm25_ranker, make_dense_ranker, make_full_ranker, make_hybrid_ranker,
)
from semsearch.eval import METRIC_KEYS, evaluate  # noqa: E402
from semsearch.split import SPLIT_PATH, load_split, make_split, select  # noqa: E402

REPORTS = Path("reports")


def _load(name: str) -> dict | None:
    p = REPORTS / name
    return json.loads(p.read_text()) if p.exists() else None


def main() -> None:
    pois = load_pois()
    queries = load_eval()
    split = load_split() if SPLIT_PATH.exists() else make_split(queries)
    tune, test = select(queries, split, "tune"), select(queries, split, "test")

    bm25_tune = evaluate(make_bm25_ranker(pois), tune)
    dense_tune = evaluate(make_dense_ranker(pois), tune)
    hybrid_tune = evaluate(make_hybrid_ranker(pois), tune)
    full = make_full_ranker(pois)
    full_test = evaluate(full, test)

    lat = _load("latency.json")
    rob = _load("robustness.json")

    def row(cell: dict) -> str:
        return " | ".join(f"{cell[k]:.3f}" for k in METRIC_KEYS)

    g1 = bm25_tune["overall"]["recall@5"]
    g2_ok = hybrid_tune["overall"]["ndcg@5"] > max(bm25_tune["overall"]["ndcg@5"],
                                                    dense_tune["overall"]["ndcg@5"])
    g3n, g3r = full_test["overall"]["ndcg@5"], full_test["overall"]["recall@3"]
    ci = full_test["ci"]

    L = ["# Metrics report", "",
         "Generated by `scripts/report_metrics.py`. Weights tuned on **tune** only; the "
         "held-out **test** split is evaluated once per milestone (NFR-6).", "",
         "## Quality gates", "",
         "| Gate | Metric | Split | Result | Threshold | Pass |",
         "|---|---|---|---|---|---|",
         f"| G1 | BM25 Recall@5 | tune | {g1:.3f} | ≥0.55 | {'✅' if g1 >= 0.55 else '❌'} |",
         f"| G2 | hybrid NDCG@5 > max(bm25,dense) | tune | {hybrid_tune['overall']['ndcg@5']:.3f} "
         f"> {max(bm25_tune['overall']['ndcg@5'], dense_tune['overall']['ndcg@5']):.3f} | > | "
         f"{'✅' if g2_ok else '❌'} |",
         f"| G3 | full NDCG@5 / Recall@3 | **test** | {g3n:.3f} / {g3r:.3f} | ≥0.80 / ≥0.75 | "
         f"{'✅' if g3n >= 0.80 and g3r >= 0.75 else '❌'} |"]
    if lat:
        L.append(f"| G4 | warm p95 latency | 60 | {lat['warm_ms']['p95']} ms | <200 ms | "
                 f"{'✅' if lat['g4_passed'] else '❌'} |")
    if rob:
        L.append(f"| G5 | robustness | all+adv | {rob['checked']} checks, {len(rob['failures'])} fail "
                 f"| 0 fail | {'✅' if rob['g5_passed'] else '❌'} |")

    L += ["", "## Held-out test headline (full pipeline)", "",
          f"n={full_test['n']} · NDCG@5 **{g3n:.3f}** (95% CI {ci['lo']:.3f}–{ci['hi']:.3f}) · "
          f"Recall@3 {g3r:.3f} · Recall@5 {full_test['overall']['recall@5']:.3f} · "
          f"MRR {full_test['overall']['mrr']:.3f}", "",
          "### Per-difficulty (test)", "",
          "| Difficulty | n | " + " | ".join(METRIC_KEYS) + " |",
          "|---|---|" + "---|" * len(METRIC_KEYS)]
    for d in ("Hard", "Medium", "Easy"):
        c = full_test["by_difficulty"].get(d)
        if c:
            L.append(f"| {d} | {c['n']} | {row(c)} |")
    L += ["", "### Per-query-category (test)", "",
          "| Category | n | " + " | ".join(METRIC_KEYS) + " |",
          "|---|---|" + "---|" * len(METRIC_KEYS)]
    for k, c in sorted(full_test["by_category"].items(), key=lambda kv: -kv[1]["n"]):
        note = " _(n=1, anecdotal)_" if c["n"] == 1 else ""
        L.append(f"| {k}{note} | {c['n']} | {row(c)} |")
    L += ["", "See also: `ablation-tune.md`, `embedding-choice.md`, `latency.json`, "
          "`robustness.json`.", ""]

    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / "metrics.md"
    out.write_text("\n".join(L), encoding="utf-8")
    print("\n".join(L))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
