"""Sample-query showcase (SPEC §7 deliverable; PRD FR-9, deliverable #4).

Runs representative Vietnamese queries across the categories/skills through the
full pipeline and writes reports/sample-queries.md: parsed intent + top-5 ranked
results with reasons and the top-3 driving signals. Script-generated (CLAUDE.md).

  python scripts/sample_queries.py
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from semsearch.data import load_pois  # noqa: E402
from semsearch.pipeline import FullPipeline  # noqa: E402

REPORTS = Path("reports")

# Representative demo queries spanning the 8 eval categories + skills. These are
# illustrative queries (not mapped to any expected ids) — no eval fitting.
QUERIES = [
    ("Semantic / work", "quán cà phê yên tĩnh để làm việc"),
    ("Location-aware", "cafe có wifi gần hồ gươm"),
    ("Intent (no category word)", "nơi hẹn hò lãng mạn có view đẹp"),
    ("Utility + time", "cây xăng 24/7 gần đây"),
    ("Attribute + location", "khách sạn gần biển Đà Nẵng"),
    ("Attribute (family)", "quán ăn phù hợp gia đình"),
    ("Category + district", "trung tâm thương mại ở quận 1"),
    ("Non-accented", "quan cafe yen tinh gan q1"),
    ("Time (late-night)", "nhà thuốc mở khuya"),
    ("Discovery / check-in", "điểm check-in sống ảo ở Đà Lạt"),
    ("Location (landmark)", "ATM gần chợ Bến Thành"),
    ("Mixed language", "coffee shop with wifi to work"),
]

SIG_LABEL = {"semantic": "ngữ nghĩa", "attributes": "thuộc tính", "distance": "khoảng cách",
             "rating": "đánh giá", "popularity": "phổ biến", "open_now": "đang mở", "review": "tags"}


def main() -> None:
    pipe = FullPipeline(load_pois())
    lines = ["# Sample queries — ranked results with explanations",
             "", "Generated by `scripts/sample_queries.py` (full pipeline, local bge-m3).", ""]
    for label, q in QUERIES:
        intent, results = pipe.search(q, k=5)
        lines.append(f"## {label} — “{q}”")
        bits = []
        if intent.category:
            bits.append(f"category=**{intent.category}**")
        if intent.required_attrs:
            bits.append("attrs=" + ", ".join(f"`{a}`" for a in intent.required_attrs))
        if intent.anchor:
            bits.append(f"anchor=**{intent.anchor.name}**")
        lines.append("_intent:_ " + (" · ".join(bits) if bits else "(free-text)"))
        lines.append("")
        for i, r in enumerate(results, 1):
            top3 = sorted(r.breakdown.items(), key=lambda kv: kv[1], reverse=True)[:3]
            sig = ", ".join(f"{SIG_LABEL[k]} {v:.2f}" for k, v in top3)
            reasons = " · ".join(r.reasons)
            lines.append(f"{i}. **{r.poi.name}** ({r.poi.category}, {r.poi.district}) — "
                         f"score {r.score:.3f}")
            lines.append(f"   - {reasons}")
            lines.append(f"   - top signals: {sig}")
        lines.append("")
    REPORTS.mkdir(parents=True, exist_ok=True)
    out = REPORTS / "sample-queries.md"
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {out}  ({len(QUERIES)} queries)")


if __name__ == "__main__":
    main()
